### ISSUE TITLE
end can be undefined

### ISSUE THREAD

**Issue by gr7ffo** [fau-fablab/getraenkeliste#4]
as stated in https://github.com/fau-fablab/getraenkeliste/blob/master/runme.py#L129

**Comment by sedrubal** [comment]
https://github.com/fau-fablab/getraenkeliste/blob/master/runme.py#L129

**Comment by gr7ffo** [comment]
end cannot be undefined, because it gets defined for each line in the `if j == 0` section of the for-loop
